### ISSUE TITLE
instaR / instar

### ISSUE THREAD

**Issue by chainsawriot** [JBGruber/instr#5]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
available::available_on_cran("instar")
```

**Comment by JBGruber** [comment]
Thanks. I forgot that capitalisation does not matter for CRAN. Very annoying.
